[build]
  functions = "netlify/functions"
  publish = "dist"
  command = "npm run build"

[dev]
  functions = "netlify/functions"

[functions]
node_bundler = "esbuild"
external_node_modules = ["fetch-blob", "formdata-polyfill"]
node_version = "18"

[functions."create_slip_scheduled"]
schedule = "*/10 * * * *"